apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-monapplicationb-monapplicationb-backend-deployment
  namespace: dev-monapplicationb-monapplicationb-backend
  labels:
    app: dev-monapplicationb-monapplicationb-backend
spec:
  selector:
    matchLabels:
      app: dev-monapplicationb-monapplicationb-backend
  template:
    metadata:
      labels:
        app: dev-monapplicationb-monapplicationb-backend
    spec:
      containers:
        - name: dev-monapplicationb-monapplicationb-backend
          image: corentin35/monapplicationb-monapplicationb-backend:develop-${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          resources:
            requests:
              cpu: '300m'
              memory: '400Mi'
            limits:
              cpu: '600m'
              memory: '800Mi'
      imagePullSecrets:
        - name: regcred
