apiVersion: v1
kind: Service
metadata:
  name: staging-monapplicationb-monapplicationb-backend-service
  namespace: staging-monapplicationb-monapplicationb-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: staging-monapplicationb-monapplicationb-backend
