apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-monapplicationb-monapplicationb-backend-cert
  namespace: prod-monapplicationb-monapplicationb-backend
spec:
  secretName: prod-monapplicationb-monapplicationb-backend-tls
  dnsNames:
    - monapplicationb.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
