apiVersion: v1
kind: Service
metadata:
  name: prod-monapplicationb-monapplicationb-backend-service
  namespace: prod-monapplicationb-monapplicationb-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: prod-monapplicationb-monapplicationb-backend
